version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: qa_nginx
    ports:
      - "8001:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/usr/src/app
    depends_on:
      - web
  web:
    build: .
    container_name: qa_django
    command: bash -c "pip3 install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && gunicorn Quasar.wsgi --timeout=3600 --workers=3 --threads=3 --worker-connections=1024 -b 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"
