# Generated by Django 4.2.2 on 2023-07-10 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiconfig',
            name='temperature',
            field=models.FloatField(default=0.3, help_text='\n        Temperature range will be 0 - 1.<br>\n        <strong>Note:</strong> Temperature changes in GPT APIs affect output randomness:<br>\n        &emsp;&emsp;&emsp;higher temperature increases creativity, lower temperature promotes coherence.\n        ', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
